### ISSUE TITLE
Issue with syntax coloring when Japanese(UTF8) letters are included

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#31] opened 2020-10-22 07:30 UTC
Logged by @IRISMeister at https://github.com/intersystems-community/vscode-objectscript/issues/411 with repro.

**Comment by gjsjohnmurray** [comment] 2020-10-22 07:59
Images from a repro from me:

![image](https://user-images.githubusercontent.com/6726799/96842195-a1cf9680-1444-11eb-8e45-9e523b8c3a7c.png)

One of the faulty tokens:
![image](https://user-images.githubusercontent.com/6726799/96842332-d17e9e80-1444-11eb-8122-51759fe8b566.png)

**Comment by daimor** [comment] 2020-10-22 08:22
The issue is just in incorrect measure of the size of Unicode symbols. 

Let's try with Cyrillic
```objectscript
Property тест As %String;
```
I'm surely know, that any of these chars are two bytes in size.
So, it says 8 chars, instead of 4 chars, while 8 just bytes
![image](https://user-images.githubusercontent.com/1212251/96843615-33480400-1457-11eb-9f06-b3b70c21784a.png)

And I suppose, that Japanese have 3 bytes per char. So we have 15 chars while expected 5
```objectscript
Property 商品コード As %String;
```
![image](https://user-images.githubusercontent.com/1212251/96843873-799d6300-1457-11eb-9b3b-f0944b5e283e.png)

BTW, in my case, I don't see syntax errors, just not correct coloring, due to the wrong length calculation.
![image](https://user-images.githubusercontent.com/1212251/96844339-0fd18900-1458-11eb-93e7-e8155e3796d2.png)

In comparing with ASCII line
![image](https://user-images.githubusercontent.com/1212251/96844871-b74ebb80-1458-11eb-8b76-fd86051188f4.png)

**Comment by gjsjohnmurray** [comment] 2020-10-22 08:50
> BTW, in my case, I don't see syntax errors, just not correct coloring, due to the wrong length calculation.

Have you set something to stop LS from reporting "Class does not exist" problems?

**Comment by daimor** [comment] 2020-10-22 08:52
I just was offline ))
With no server running at all.

**Comment by IRISMeister** [comment] 2020-10-22 09:44
That correct. Each Japanese char is represented by 3 bytes in UT8 encoding.
USER>zzdump $ZCVT("商品コード","O","UTF8")
 
0000: E5 95 86 E5 93 81 E3 82 B3 E3 83 BC E3 83 89            å..å..ã.³ã.¼ã..

Please note, mixture of Japanese and ascii/numeric is also a valid token. 
USER>zzdump $ZCVT("商品CODE","O","EUC")
 
0000: BE A6 C9 CA 43 4F 44 45                                 ¾¦ÉÊCODE

If encoding matters, VSCode supports, in addition to UTF8, 2 major Japanese encodings, SJIS(which was mainly used on Windows/Mac) and EUC(Unix). As you can see these encoding uses two bytes per character,
USER>zzdump $ZCVT("商品コード","O","SJIS")
 
0000: 8F A4 95 69 83 52 81 5B 83 68                           .¤.i.R.[.h
USER>zzdump $ZCVT("商品コード","O","EUC")
 
0000: BE A6 C9 CA A5 B3 A1 BC A5 C9                           ¾¦ÉÊ¥³¡¼¥É

If we need/want to pick one as the supported Japanese encoding for Language Server, UTF8 is the right one because this is what IRIS Server exports via its REST/API (and is universal nowadays).

**Comment by gjsjohnmurray** [comment] 2020-10-28 15:40
@isc-bsaviano is a resolution for this issue in sight? At the moment LS isn't showing its best face to folk who use characters above ASCII 127.

**Comment by isc-bsaviano** [comment] 2020-10-28 15:41
Yes it is. This will be fixed in version 1.0.4, which I'm hoping to get out today.

**Comment by isc-bsaviano** [comment] 2020-10-28 16:46
@gjsjohnmurray @IRISMeister Fixed in version 1.0.4

**Closed by isc-bsaviano** 2020-10-28 16:46 UTC
