### ISSUE TITLE
Language Server crashes with "Unhandled method intersystems/server/resolveFromUri" error

### ISSUE THREAD

**Issue by ebromberg** [intersystems/language-server#241] opened 2022-08-02 13:59 UTC
I was having issues with the Outline Pane not populating. Then the last time I tried to save my code, I got a message that the Language Server Crashed and review the log. Attached is the log file. Not sure if it was needed but I was just trying with a simple mac file that looks like:
ROUTINE xCleanup

xCleanup

Begin(test=1) { W "ERIC" 
 W "ERIC"
 q 1 
}
[Languageserver.txt](https://github.com/intersystems/language-server/files/9242825/Languageserver.txt)

**Comment by isc-bsaviano** [comment] 2022-08-02 14:23
@ebromberg If you turn on tracing for the Language Server (set `"intersystems.language-server.trace.server"` to `"messages"` or `"verbose"`), what request is failing that causes the crash? I just created a new routine with the code in your issue description and everything looks fine. I'm using version 2.0.5.

**Comment by ebromberg** [comment] 2022-08-02 14:49
I am also using 2.0.5. I turned on verbose and it seems to just dump the same messages as before. 
Attached is the dump file from this time.
[server2.txt](https://github.com/intersystems/language-server/files/9243249/server2.txt)

**Comment by isc-bsaviano** [comment] 2022-08-02 15:08
@ebromberg When does the crash occur? Immediately after opening the routine or after a certain edit/cursor movement?

**Comment by isc-bsaviano** [comment] 2022-08-02 15:32
Can you check that the main extension (`InterSystems ObjectScript`) is active when you open these files? The reported error in your logs is:

```
a [Error]: Unhandled method intersystems/server/resolveFromUri
    at c:\Users\EBromberg\.vscode\extensions\intersystems.language-server-2.0.5-win32-x64\server\out\server.js:2:716302
    at c:\Users\EBromberg\.vscode\extensions\intersystems.language-server-2.0.5-win32-x64\server\out\server.js:2:716596
    at Immediate.<anonymous> (c:\Users\EBromberg\.vscode\extensions\intersystems.language-server-2.0.5-win32-x64\server\out\server.js:2:716958)
```
That custom request from the server to the client calls the main extensions exported `serverForUri()` API. I'm thinking that if the extension isn't active the API call will fail, causing the "unhandled method" error.
cc @gjsjohnmurray

**Comment by ebromberg** [comment] 2022-08-02 15:39
How do I check the extension is active? I think it would be since I click on the ObjectScript to connect the folder to a server and namespace.
What is odd is that another folder pointing to the same server and namespace doesn't have any issues. Outline works and no crashing.

**Comment by isc-bsaviano** [comment] 2022-08-02 15:46
@ebromberg You can check if the extension is active by opening the extensions view (click the four squares logo in the activity bar in the far left of your window) and hovering over the extension name. If you don't see an Activation Time then the extension isn't activated. It's possible that the extension will be active now but it wasn't when the Language Server activated and was trying to respond to that request.

**Comment by ebromberg** [comment] 2022-08-02 16:00
I restarted VSCode and when it reopened, I got prompted to put in password to connect to Cache. The extensions tab was opened and before I did anything, I can see the Objectscript extension has an activation time. However the language server does not.
So then I tried making a new MAC routine by doing:
New Text File, picking Objectscript as the language.
Typed in:
ROUTINE xTestme

xTestme
Begin() { q 1 }

Saved as xTestme.mac

Language Server is still not active. 
I didn't get any error
If I refresh my connection to the cache server, that's when I get the error.
Language Server still shows as not active.

**Comment by ebromberg** [comment] 2022-08-02 17:07
I was able to figure this out. On a folder where it was working, I compared the settings.json to this folder (where it doesn't work). Once I added in this line:
    "workbench.colorTheme": "InterSystems Default Dark"

Everything is working just fine. Not sure why but I did confirm if I take that line out, the problem reappears.

**Comment by isc-bsaviano** [comment] 2022-08-02 17:18
@ebromberg I'm not sure why that would fix the problem. I just commented out that line in my user settings and restarted VS Code and I still can't reproduce your issue. I saw the prompt to select the default InterSystems theme. Did you see that before your error appears? If not, do you have `"intersystems.language-server.suggestTheme"` set to `false` in your user or workspace settings?

**Comment by ebromberg** [comment] 2022-08-02 18:10
I never got a prompt to select the default Intersystems theme. There are no entries for "intersystems.language-server.suggestTheme" in either the user or workspace settings.json.
![image](https://user-images.githubusercontent.com/48656450/182444328-e41c6889-351e-48c2-a220-ef893d858458.png)

**Comment by isc-bsaviano** [comment] 2022-08-02 18:30
@ebromberg Just to clarify, you only see this crash when you open a workspace that does not use an InterSystems theme, and you are not prompted to change the theme before the crash?

**Comment by ebromberg** [comment] 2022-08-02 18:32
I am not prompted to change the theme. It doesn't always crash when I open the workspace. It seems like the Language Server never starts and then I force a Refresh causes the error.

**Comment by isc-bsaviano** [comment] 2022-08-02 18:48
@ebromberg Would it be possible for you to record your screen while you open the workspace until you see the crash?

**Comment by ebromberg** [comment] 2022-08-02 19:27
I recorded the ~3 min video but I cannot attach it here. Its too big of a file.

**Comment by isc-bsaviano** [comment] 2022-08-02 19:30
If you try to compress it to a .zip does it shrink enough?

**Comment by ebromberg** [comment] 2022-08-02 19:33
[Get Started - Visual Studio Code 2022-08-02 15-20-13.zip](https://github.com/intersystems/language-server/files/9245129/Get.Started.-.Visual.Studio.Code.2022-08-02.15-20-13.zip)

**Comment by isc-bsaviano** [comment] 2022-08-02 19:34
Thanks, I really appreciate your help in tracking this down. I'll watch the screen recording now and see if I notice anything.

**Comment by isc-bsaviano** [comment] 2022-08-02 20:10
I just looked at the video. The first thing I want to address is the uncaught errors from the main extension (timestamp 1:45). Those are coming from the `onDidChangeTextEditorSelection()` handler. The document symbol command is returning `undefined` and we assumed that it wouldn't. I believe that the document symbol provider is failing due to the new routine being modified incorrectly after it is created (timestamp 1:19). That might be caused by the the `onDidCreateFiles()` handler. I will create an issue in the main extension repo for those but since they aren't causing the Language Server crash I will consider the out of scope for now.

I believe that the Language Server crash is being caused by your authentication method. The main extension's `serverForUri()` method is trying to resolve the password but since you haven't filled in the prompt it's not returning and the LS crashes. If you store the password in your `intersystems.servers` setting object using the "password" key, or use the server manager to store it securely in the OS keychain, do you still see this error when you restart and follow the same steps?

**Comment by ebromberg** [comment] 2022-08-02 22:03
I just happened to see those uncaught errors and figured I would point it out in case it was useful.

I just tried both storing my password in the keychain and also in the intersystems.server object. I then restarted VSCode and followed same steps in the video and LS still crashes.

**Comment by isc-bsaviano** [comment] 2022-08-03 12:23
@ebromberg Thanks for trying that. Since we still don't know why `serverForUri()` isn't returning I've attached a version of the main extension that has `serverForUri()` heavily logged. To install it, simply unzip it and drag the VSIX into the extensions tab of your VS Code and reload it. With the modified extension installed and your password in your settings.json file can you re-open the workspace where the error is without any other files open, repeat your steps to produce the error and then attach the entire contents of the `ObjectScript` Output channel to your next message? I really appreciate your help and I apologize for asking you to do this but since I can't reproduce your issue this is the only way I can track it down.

[vscode-objectscript-1.8.2-SNAPSHOT.vsix.zip](https://github.com/intersystems/language-server/files/9251188/vscode-objectscript-1.8.2-SNAPSHOT.vsix.zip)

**Comment by ebromberg** [comment] 2022-08-03 12:51
No worries. I installed this version of the plugin, did a reload. Opened the folder I have been working in (no files were reopened), followed same steps as video. There is no additional logging in the Objectscript output. It just shows the compilation message. 
I did double check this version of the extension did install. If I hover over it in extensions, it shows as v1.8.2-snapshot.

**Comment by isc-bsaviano** [comment] 2022-08-03 13:01
@ebromberg So the error appeared but nothing was logged to the `ObjectScript` output channel? If you search through the Language Server output for "[Error]" (you can click on the output window and Ctrl-F) do you see the same "unhandled method" error as earlier in this thread?

**Comment by ebromberg** [comment] 2022-08-03 14:24
Correct. There is nothing in Objectscript about Getting server for {uri}. And in the LS output I still see the unhandled exception error message. I am attaching a video of what I did, just in case I might have missed something.
[debug.zip](https://github.com/intersystems/language-server/files/9252097/debug.zip)

**Comment by isc-bsaviano** [comment] 2022-08-03 14:50
@ebromberg Thanks for the video. Since the main extension exported API is never called I'm thinking that the bug must be in the Language Server client side code that gets the exported API and handles this method. I modified that code to make sure the main extension is active before we try to use its API. This LS version will also log "Called resolveFromUri()" when that method is called and a JSON-stringified main extension exported API. Please install this and give it a try. 

[language-server-2.0.6-beta.1.vsix.zip](https://github.com/intersystems/language-server/files/9252521/language-server-2.0.6-beta.1.vsix.zip)

**Comment by ebromberg** [comment] 2022-08-03 17:39
I tried that extension and once I reload VSCode before doing anything, the LS server crashes.
![image](https://user-images.githubusercontent.com/48656450/182673248-bc748095-458c-45e0-9210-4615ab4fe864.png)
Here's a copy from the LS output pane too.
[lsdebug.txt](https://github.com/intersystems/language-server/files/9253847/lsdebug.txt)

**Comment by isc-bsaviano** [comment] 2022-08-03 17:46
Sorry, I made a mistake. I gave you a VSIX with a macx64 binary instead of windows. Try this one.

[language-server-win32-x64-2.0.6-beta.2.vsix.zip](https://github.com/intersystems/language-server/files/9253879/language-server-win32-x64-2.0.6-beta.2.vsix.zip)

**Comment by ebromberg** [comment] 2022-08-03 18:29
I put that version in and now I can't replicate the error. I did search the LS output and saw the "Called resolveFromUri()" get logged.

**Comment by isc-bsaviano** [comment] 2022-08-03 18:30
Awesome! I will clean my code up and get it committed. Thanks for your help debugging this.

**Comment by ebromberg** [comment] 2022-08-03 18:33
No problem. Appreciate all the help on this.

**Closed** 2022-08-03 18:40 UTC
