### ISSUE TITLE
If you add [unique] clause to index it LS suggests wrong completion

### ISSUE THREAD

**Issue by evshvarov** [intersystems/language-server#167] opened 2021-06-11 10:53 UTC
It inserts the template property instead of unique completion.

to reproduce add an index with the unique clause, e.g.:

Index NameIndex on Name [unique];

**Comment by gjsjohnmurray** [comment] 2021-06-11 11:43
From my Discord response to @evshvarov:
>It is Language Server's responsibility to provide CompletionItems.
>The 'Unique' snippet is provided by the vscode-objectscript extension. Perhaps it was a poor choice of snippet name.

**Comment by gjsjohnmurray** [comment] 2021-06-11 11:46
@isc-bsaviano does LS yet provide completions for [index keywords](https://docs.intersystems.com/irislatest/csp/docbook/Doc.View.cls?KEY=ROBJ_index)?

**Comment by isc-bsaviano** [comment] 2021-06-11 12:25
@gjsjohnmurray Yes, we do.

**Comment by gjsjohnmurray** [comment] 2021-06-11 17:02
@evshvarov if you enter a space after the [ and before you start typing Unique does the completion work as expected?

**Comment by isc-bsaviano** [comment] 2021-06-16 18:50
@evshvarov When I begin typing `[ U` at the end of an Index definition, I correctly see the `Unique` keyword suggestion from the LS. I don't see the main extension snippet. I'm closing this issue because it's neither reproducible by me nor is a bug in this extension even if I could reproduce it.

**Closed by isc-bsaviano** 2021-06-16 18:50 UTC

**Comment by gjsjohnmurray** [comment] 2021-06-16 20:18
@isc-bsaviano do you see the issue if you omit the space between `[` and `U' and instead type `[U` ?

**Comment by isc-bsaviano** [comment] 2021-06-17 12:17
@gjsjohnmurray Yes, in that case I see the `Unique Property` snippet suggested. I don't see anything from the LS, which is expected because space is the trigger character.
