### ISSUE TITLE
Go to definition (F12) throwing error

### ISSUE THREAD

**Issue by Nemesis1990** [intersystems/language-server#34] opened 2020-10-22 12:44 UTC
When I try to use "Go to definition" it gives me this error:

![image](https://user-images.githubusercontent.com/6547466/96871993-4f599e80-1473-11eb-8ecc-4a208f6003b0.png)

![image](https://user-images.githubusercontent.com/6547466/96871937-3cdf6500-1473-11eb-89c6-fb077fdb04b8.png)

I can't provide a better log. That's the only message I found that is related to this message.

VSCode is up to date and the plugins also. It worked without the LSP before (VSCode Objectscript only). Class is compiled on server and is in my VSCode-Project.

Somehow it works with System-Libs like %Library.Date:

![image](https://user-images.githubusercontent.com/6547466/96872472-f9392b00-1473-11eb-8501-12a3673d4c22.png)

**Comment by Nemesis1990** [comment] 2020-10-22 12:57
My classes having .CLS and not .cls as extension. Could be the problem here.

**Comment by isc-bsaviano** [comment] 2020-10-22 12:58
@Nemesis1990 Can you check the logs for the main vscode-objectscript extension after the go to definition request fails? If the URI that we're trying to jump to is there I may be able to see if it's malformed.

**Comment by daimor** [comment] 2020-10-22 13:01
@Nemesis1990 could you say, what OS you using, is filesystems there case sensitive?

**Comment by Nemesis1990** [comment] 2020-10-22 13:05
@isc-bsaviano Log from plugin is empty after error. The only output I have is in the 2nd picture from Log (Window)

@daimor It's Windows 10 so it is case sensitive. I think the case of the file-extension is the problem

**Comment by isc-bsaviano** [comment] 2020-10-22 13:23
@Nemesis1990 Can you please go to your settings, turn the Language Server trace to verbose, try your go to definition again and look for the response from the server in the "InterSystems Language Server" Output feed and post it here? I want to make sure the server is returning the correct URI

**Comment by Nemesis1990** [comment] 2020-10-22 13:28
@isc-bsaviano 

Interesting. I'm in my Workspace-Folder "Online-Iris" but it mentions "Online-Artikelserver" later on. Class exists in both folders. Different servers.

```[Trace - 15:25:21] Sending request 'textDocument/definition - (406)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/jochen.roese/Documents/workspaces/Online-Iris/src/API/Admin.CLS"
    },
    "position": {
        "line": 981,
        "character": 27
    }
}


[Trace - 15:25:21] Received request 'intersystems/uri/localToVirtual - (271)'.
Params: "file:///c%3A/Users/jochen.roese/Documents/workspaces/Online-Iris/src/API/Admin.CLS"


[Trace - 15:25:21] Sending response 'intersystems/uri/localToVirtual - (271)'. Processing request took 0ms
Result: "objectscript://online-artikelserver/"


[Trace - 15:25:21] Received response 'textDocument/definition - (406)' in 11ms.
Result: {
    "uri": "objectscript://online-artikelserver/API/Router.cls",
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 0,
            "character": 0
        }
    }
}```

**Comment by gjsjohnmurray** [comment] 2020-10-22 13:38
@Nemesis1990 what does c:\Users\jochen.roese\Documents\workspaces\Online-Iris\.vscode\settings.json file contain? And does your user-level settings.json file contain an `objectscript.conn` object? I assume it does contain an `intersystems.servers` object that defines a server called `online-artikelserver`

**Comment by gjsjohnmurray** [comment] 2020-10-22 13:40
Another thought - perhaps you are suffering from #33 which causes the server to run out of licenses. What does your license usage look like in Portal on the server? And the CSP/WebApp Sessions list?

**Comment by Nemesis1990** [comment] 2020-10-22 13:42
@gjsjohnmurray 
I have it in /Online-Iris/.vscode/settings.json

```
{
    "objectscript.conn": {
        "active": true,
        "label": "LOCAL",
        "host": "localhost",
        "port": 57772,
        "username": "_SYSTEM",
        "password": "SYS",
        "ns": "ONLINE",
        "version": 3,
        "https": false
    }
}
```

settings.json in online-artikelserver:

```
{
    "objectscript.conn": {
        "active": true,
        "host": "10.8.8.222",
        "port": 57772,
        "username": "_SYSTEM",
        "password": "SYS",
        "ns": "SYA",
        "https": false,
        "docker-compose": {
            "service": "",
            "internalPort": 52773,
            "file": "docker-compose.yml"
        },
        "links": {}
    }
}
```

I'm not using the new features of the server-plugin.

**Comment by Nemesis1990** [comment] 2020-10-22 13:44
> Another thought - perhaps you are suffering from #33 which causes the server to run out of licenses. What does your license usage look like in Portal on the server? And the CSP/WebApp Sessions list?

I don't think it's a license limitation. Everything else working properly at the moment. 
I have this license in my local installation:

```
Produkt=Server
Lizenztyp=Core Capacity
Server=Multi
Plattform=X86-64(Windows)
Lizenzeinheiten=0
Lizensierte Cores=256
Authorized Cores=256
Extended Features=02091800
- Interoperability
- Analytics Run
- NLP
- InterSystems IRIS
Development
```

**Comment by gjsjohnmurray** [comment] 2020-10-22 13:49
> settings.json in online-artikelserver:
> 
> ```
> {
>     "objectscript.conn": {
>         "active": true,
> ...
> ```

Is the full filename that this comes from c:\Users\jochen.roese\Documents\workspaces\\**online-artikelserver**\\.vscode\settings.json ?

**Comment by Nemesis1990** [comment] 2020-10-22 13:50
@gjsjohnmurray  yes it is

**Comment by gjsjohnmurray** [comment] 2020-10-22 13:51
And are you using "Open Folder" in VSCode? Or have you defined a .code-workspace file? If the latter, please post its contents here (mask any confidential info since this is a public repo).

**Comment by Nemesis1990** [comment] 2020-10-22 13:53
I'm using workspaces. 
This is the .code-workspace file:
```
{
	"folders": [
		{
			"path": "Online-Cache"
		},
		{
			"path": "Online-Artikelserver"
		},
		{
			"path": "Online-Iris"
		}
	],
	"settings": {
		"objectscript.conn.active": false,
		"dimmer.enabled": false
	}
}
```

**Comment by Nemesis1990** [comment] 2020-10-22 13:57
Ok. In "Online-Artikelserver" the "Go to defintion" works properly for every class. 

When I change between the projects the connection in the bottom of VSCode shows the correct server it should connect to.

**Comment by gjsjohnmurray** [comment] 2020-10-22 14:04
OK, so the file you had open and tried F12 from had been opened from your Online-Cache root of your multiroot workspace, but when the language-server extension (LS) asked the vscode-objectscript one (OS) for a uri it was incorrectly given `objectscript://online-artikelserver/`. Then LS asked your server at 10.8.8.222 for the class and had some kind of problem.

In the ObjectScript Explorer view in VSCode there should be three root folders. Can you view classes in all of them?

**Comment by Nemesis1990** [comment] 2020-10-22 14:14
@gjsjohnmurray the explorer view shows me everything as it should be. Every different server has classes in them.

**Comment by gjsjohnmurray** [comment] 2020-10-22 14:37
@Nemesis1990 I think LS is using this API function in OS (@isc-bsaviano  will confirm):

https://github.com/intersystems-community/vscode-objectscript/blob/81a8dfac58e34860b06bd04f9522c602408c76c1/src/extension.ts#L848-L866

Navigating through the code on GH I haven't yet worked out how an input uri of `file:///c%3A/Users/jochen.roese/Documents/workspaces/Online-Iris/src/API/Admin.CLS` ends up returning `objectscript://online-artikelserver/` after looking at your config settings. Still checking...

**Comment by isc-bsaviano** [comment] 2020-10-22 14:39
@gjsjohnmurray The client calls that API (objectScriptApi.serverDocumentUriForUri()) when it receives a "intersystems/uri/localToVirtual" request from the server.

**Comment by gjsjohnmurray** [comment] 2020-10-22 14:51
@Nemesis1990 please download https://github.com/intersystems-community/vscode-objectscript/releases/download/v1.0.2-beta.2/vscode-objectscript-1.0.2-beta.2.vsix and install that. I think there's a chance that one of the changes in it may help. My theory is the mixed-case folder names aren't being handled correctly in 1.0.1

**Comment by Nemesis1990** [comment] 2020-10-22 14:54
@gjsjohnmurray That didn't help. Same error. 
![image](https://user-images.githubusercontent.com/6547466/96889706-28a56300-1487-11eb-8fbf-ba152594f3c8.png)

**Comment by gjsjohnmurray** [comment] 2020-10-22 14:57
@Nemesis1990 thanks for trying anyway. I'm going to set up an equivalent config here and try to reproduce the problem.

**Comment by gjsjohnmurray** [comment] 2020-10-22 16:10
@isc-bsaviano the bug is here:

https://github.com/intersystems/language-server/blob/638a496c5d620457b35e6a00680b1c75123c776c/client/src/extension.ts#L61

The API expects a uri but you are passing a string.

Call it with `Uri.parse(uri)` instead of `uri`. See a few lines earlier for a similar call, which I recall got fixed in an earlier beta.

**Comment by isc-bsaviano** [comment] 2020-10-22 16:13
Yup, that's it. I'll fix this.

**Closed** 2020-10-22 16:41 UTC
Labels: bug
