### ISSUE TITLE
Ability to ignore errors of classes that may be in another namespace

### ISSUE THREAD

**Issue by isc-kiyer** [intersystems/language-server#97] opened 2020-12-10 10:08 UTC
Enhancement request:
Code may sometimes switch to another namespace (using zn or set $namespace) and then call methods that only exist in that namespace and not in the source one. As an example, code may switch to the %SYS namespace and access a class in the "Security" package which is flagged as an error as seen below:

<img width="566" alt=" 2020-12-10 at 15 33 19" src="https://user-images.githubusercontent.com/75783557/101757832-9cfe9900-3afd-11eb-9cf5-9ff6f699cc67.png">

There should be a setting to enable ignoring such errors.

I am using v1.0.5 on a Mac.

**Comment by isc-bsaviano** [comment] 2020-12-10 13:27
Duplicate of #77

**Closed by isc-bsaviano** 2020-12-10 13:27 UTC
Labels: duplicate
