### ISSUE TITLE
Method completion missing for inherited methods (possibly in edge case(s)?)

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/language-server#280] opened 2023-05-16 12:39 UTC
Consider:
```
                set workMgr = $System.WorkMgr.%New()
                $$$ThrowOnError(workMgr.Queue("##class(Some.Class).SomeMethod"))
                do workMgr.WaitForComplete()
```
I don't get help with classmethods of $System.WorkMgr at all. (Maybe this is part of #123 depending on what you mean by "system"?)

So switch over to `##class(%SYSTEM.WorkMgr).%New()` instead - the following is true in either case. If I type workMgr.Wait it won't offer WaitForComplete as an option.

Possible root cause:
`WaitForComplete` is inherited from `%SYSTEM.AbstractWorkMgr`, but `%SYSTEM.WorkMgr` has:
`Class %SYSTEM.WorkMgr Extends AbstractWorkMgr`

Not sure if the issue here is %SYSTEM or the context for short package names.

I also don't get completion help/assistance inside the $$$ThrowOnError macro, but that's probably a separate issue.

**Comment by isc-bsaviano** [comment] 2023-05-16 12:50
@isc-tleavitt This is a duplicate of #242. Some system classes don't have inheritance resolved in `^oddCOM` and there's nothing this extension can do about that.

**Closed by isc-bsaviano** 2023-05-16 12:50 UTC

**Comment by isc-tleavitt** [comment] 2023-05-16 12:55
@isc-bsaviano thanks, I didn't see that. Do we have an upstream issue? (I can't find one in some quick searching.)

**Comment by isc-bsaviano** [comment] 2023-05-16 12:56
I don't think we do

**Comment by isc-tleavitt** [comment] 2023-05-16 12:57
Would you mind writing one up since you have more context?

**Comment by isc-tleavitt** [comment] 2023-05-16 12:58
I feel like even if we're not using ^oddCOM to build the class descriptor we could still put the data there for reference.
