### ISSUE TITLE
Language Server v2.0.0 Crashes Repeatedly Upon Startup

### ISSUE THREAD

**Issue by DodgeDeBoulet** [intersystems/language-server#221] opened 2022-03-31 11:14 UTC
Reverted to 1.2.9 due to the following issue on reload (concurrent with upgrade to VSCode 1.66 system). Error:

[Error]: Unhandled method intersystems/server/resolveFromUri
    at c:\Users\jd363\.vscode\extensions\intersystems.language-server-2.0.0\server\out\server.js:2:708402
    at c:\Users\jd363\.vscode\extensions\intersystems.language-server-2.0.0\server\out\server.js:2:708696
    at Immediate.<anonymous> (c:\Users\jd363\.vscode\extensions\intersystems.language-server-2.0.0\server\out\server.js:2:709061)
    at processImmediate (node:internal/timers:464:21) {
  code: -32601,
  data: undefined
}
[Error - 7:05:11 AM] Connection to server got closed. Server will not be restarted.
[Error - 7:05:11 AM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\jd363\.vscode\extensions\intersystems.language-server-2.0.0\client\out\extension.js:2:124428)
	at Object.dispose (c:\Users\jd363\.vscode\extensions\intersystems.language-server-2.0.0\client\out\extension.js:2:207144)
	at j.handleConnectionClosed (c:\Users\jd363\.vscode\extensions\intersystems.language-server-2.0.0\client\out\extension.js:2:207332)
	at j.handleConnectionClosed (c:\Users\jd363\.vscode\extensions\intersystems.language-server-2.0.0\client\out\extension.js:2:284585)
	at t (c:\Users\jd363\.vscode\extensions\intersystems.language-server-2.0.0\client\out\extension.js:2:205526)
	at n.invoke (c:\Users\jd363\.vscode\extensions\intersystems.language-server-2.0.0\client\out\extension.js:2:126056)
	at r.fire (c:\Users\jd363\.vscode\extensions\intersystems.language-server-2.0.0\client\out\extension.js:2:126821)
	at Z (c:\Users\jd363\.vscode\extensions\intersystems.language-server-2.0.0\client\out\extension.js:2:112952)
	at n.invoke (c:\Users\jd363\.vscode\extensions\intersystems.language-server-2.0.0\client\out\extension.js:2:126056)
	at r.fire (c:\Users\jd363\.vscode\extensions\intersystems.language-server-2.0.0\client\out\extension.js:2:126821)
	at d.fireClose (c:\Users\jd363\.vscode\extensions\intersystems.language-server-2.0.0\client\out\extension.js:2:134707)
	at ChildProcess.<anonymous> (c:\Users\jd363\.vscode\extensions\intersystems.language-server-2.0.0\client\out\extension.js:2:145705)
	at ChildProcess.emit (node:events:402:35)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

Complete dump from Output attached.

[LanguageServerDump.txt](https://github.com/intersystems/language-server/files/8388768/LanguageServerDump.txt)

**Comment by DodgeDeBoulet** [comment] 2022-03-31 11:27
Update: Currently evaluating whether this was caused by the use of a self-signed certificate at this site. I noticed an error complaining about the cert in the output window for 1.2.9 when I reverted; a search suggested that setting http.ProxyStrictSSL to false might resolve it. I've reloaded v2.0.0 since that change and it has not generated any errors/crashes.

**Comment by DodgeDeBoulet** [comment] 2022-03-31 11:38
2nd update: Problem still exists, same error. Also, FYI:
![image](https://user-images.githubusercontent.com/4532366/161046470-6dd66761-9641-4815-a632-3afbed21e70c.png)

**Comment by isc-bsaviano** [comment] 2022-03-31 11:44
@DodgeDeBoulet I think this may be a duplicate of #219. Unfortunately the original fix for it broke HTTPS requests altogether. I'm hoping to have a fix out shortly. What OS are you on?

**Comment by DodgeDeBoulet** [comment] 2022-03-31 11:53
Hi @isc-bsaviano, My local workstation is Windows 10 x64; server is RHEL 8.5. IRIS is behind a standalone Apache server configured for TLS with self-signed certs installed on the same host if that matters (probably not 😊)

**Comment by DodgeDeBoulet** [comment] 2022-03-31 12:06
Also, FYI ... the self-signed cert is in the windows trusted store and web browsers don't complain.

**Comment by isc-bsaviano** [comment] 2022-03-31 14:18
@DodgeDeBoulet Can you try the vsix found [here](https://github.com/intersystems/language-server/issues/219#issuecomment-1084651250) and let me know if it works for you?

**Closed** 2022-03-31 14:51 UTC
