### ISSUE TITLE
Properly handle retrigger signatureHelp requests that don't contain an active signature

### ISSUE THREAD

**Issue by isc-aray** [intersystems/language-server#88] opened 2020-11-17 13:28 UTC
Issue Type: <b>Bug</b>

Sometimes while I'm writing code, I get the following error:

```
[Error - (timestamp)] Request textDocument/signatureHelp failed.
  Message: Request textDocument/signatureHelp failed with message: Cannot set property 'doc' of undefined
  Code: -32603
```

I'm not sure exactly what causes this to happen, but it seems to be related to trying to look up method documentation while inside a macro invocation. For example, the most recent occurrence was while typing the following line:

``` objectscript
    $$$QuitOnError(##SUPER())
```

I've also seen this error show up in the following code:

``` objectscript
    Do $$$AssertFailure(msg_$SYSTEM.Status.GetErrorText(sc))
```

Extension version: 1.0.5
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.97GB free)|
|Process Argv|--crash-reporter-id c8e6d92c-6dbd-4d1d-8545-8580426d5010|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isc-bsaviano** [comment] 2020-11-17 13:49
@isc-aray In those 2 examples, where is your cursor when you get the error? Inside of the ##super()/$SYSTEM.Status.GetErrorText()? Does it appear when you type inside the parentheses or after you type the opening "("?

**Comment by isc-aray** [comment] 2020-11-17 13:57
I believe it does happen after typing the opening parenthesis after ##SUPER or $SYSTEM.Status.GetErrorText. It's hard to say for certain, since it isn't reliably reproducible and it's difficult to judge these things when typing quickly.

**Comment by isc-bsaviano** [comment] 2020-11-17 13:58
@isc-aray Ok, I'll try to reproduce it.

**Comment by isc-bsaviano** [comment] 2020-11-17 14:54
@isc-aray I manually typed both of your examples but couldn't reproduce this error. When I type a line where you have nested macro/methods that both have a SignatureHelp (`$$$QuitOnError($SYSTEM.Status.GetErrorText(sc))`), typing the second `(` doesn't cause an error or open a new SignatureHelp. This is the expected behavior based on the current implementation.

**Comment by isc-aray** [comment] 2020-11-17 15:21
Unfortunately, it isn't consistent. It just happens occasionally and I'm not sure how to make it happen reliably.

**Comment by isc-bsaviano** [comment] 2020-11-17 15:24
Ok. I'll leave this issue open and if you find any more examples or a way to reproduce this let me know. I'll keep trying but there's nothing I can do if I can't examine the issue myself.

**Comment by mburstinisc** [comment] 2021-01-15 19:27
I have also gotten this error at random times.  I typically have to restart VSCode to make this error go away, it keeps occurring when saving/compiling a file when it happens.  I'm running:
VSCode 1.52.1
macOS 10.15.7
Language Server 1.0.6
Server Manager: 1.0.2
ObjectScript 1.0.8
various Iris versions

I'll see if I can find a way to reproduce, but it happens randomly for me as well

**Comment by isc-bsaviano** [comment] 2021-01-15 19:31
@mburstinisc Are you sure that you're seeing this exact error when you try to save and compile? A SignatureHelp is only triggered when you're typing certain characters, not when you save a file.

**Comment by mburstinisc** [comment] 2021-01-15 19:34
I could be wrong when I see it -- it starts to flood my output tab so it is possible that it happens frequently enough that I don't know when it is happening

**Comment by isc-bsaviano** [comment] 2021-01-15 19:38
@mburstinisc What are you typing when you first see the error pop up in the lower right corner? SignatureHelp is triggered when you type `(` or `,` but it should only return something if you're in a method or macro argument list.

**Comment by mburstinisc** [comment] 2021-01-15 19:41
I unfortunately can't say.  I didn't notice the errors happening until I went to compile my class and didn't see output saying it compiled successfully (Which is why I thought it came up then).  Is there any sort of logging that I can enable or get?

**Comment by isc-bsaviano** [comment] 2021-01-15 19:45
@mburstinisc Yes, you can trace the communication between the Language Server and VSCode client by going to Settings -> Extensionms -> InterSystems Language Server -> Trace and turning it on "verbose" ("messages" should also be fine). You'll be able to see the trace in the Output tab in the bottom pane once you select "InterSystems Language Server" from the dropdown menu.

**Comment by mburstinisc** [comment] 2021-01-15 20:28
I just had a similar error happen but it is slightly different error string.  It looks like I actually have a legit syntax error in my code that I copy/pasted, but it is causing this error

[Error - 3:16:51 PM] Request textDocument/signatureHelp failed.
  Message: Request textDocument/signatureHelp failed with message: Cannot read property 'l' of undefined
  Code: -32603 
[Error - 3:16:51 PM] Request textDocument/signatureHelp failed.
  Message: Request textDocument/signatureHelp failed with message: Cannot read property 'l' of undefined
  Code: -32603 

In this case, I have code:

	while rs.%Next(.st) {
		if ($$$ISERR(st)) {
			return st
		}
		k rowdata
		s rowtotal=0
		for i = 1:1:colcount {
			s rowdata(i) = rs.GetData(i)
			s rowtotal = rowtotal + s rowdata(i)   <------ note syntax error here
		}

		if (rowtotal) {     <---- this block is referenced below
			
		}  <----- end block referenced below

		for i = 1:1:colcount {
			w rs.GetData(i), $c(9)
			s total(i) = total(i) + rs.GetData(i)
		}
		w !
	}

I had that code with the syntax error above (which I copy/pasted from somewhere else) and then started typing the 
"if (rowtotal) { }" block of code.  

Once I corrected the above typo, I still get the error when I close a bracket.   For example, I fixed the syntax error, then deleted the block if code with "if (rowtotal) {" then re-added that code, when it completed the closing brace I saw the error.  This is not something that happens every time but it happened at least once.

**Comment by isc-bsaviano** [comment] 2021-01-15 20:47
@mburstinisc Thanks for the detailed comment. I copied your code and followed the steps but couldn't reproduce the error. If you set the trace to "verbose" and try those operations again, can you also send me the requests that produced those error responses? That way I'll have more information that can tell me what you typed and the state of the file at the time of the request. If any of the code is sensitive, you can email that request packet to me. The request packet will look like this: 
```
[Trace - 3:43:00 PM] Sending request 'textDocument/signatureHelp - (###)'.
Params: {
  ...
}
```

**Comment by mburstinisc** [comment] 2021-01-21 16:35
The following just happened to me in the middle of just writing some code, the code in this case didn't even have an error (thought I'm not sure whether the " Cannot read property 'l' of undefined" error happened before I finished typing my line of code.  I don't see the Params as part of it, though.

[Trace - 11:32:29 AM] Received response 'textDocument/foldingRange - (2690)' in 1751ms.
[Trace - 11:32:30 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:32:30 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:32:30 AM] Sending request 'textDocument/foldingRange - (2699)'.
[Trace - 11:32:30 AM] Received response 'textDocument/completion - (2691)' in 2122ms.
[Trace - 11:32:30 AM] Received response 'textDocument/foldingRange - (2692)' in 1948ms.
[Trace - 11:32:30 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:30 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:30 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:32:30 AM] Sending request 'textDocument/completion - (2700)'.
[Trace - 11:32:30 AM] Sending request 'textDocument/signatureHelp - (2701)'.
[Trace - 11:32:30 AM] Sending request 'textDocument/foldingRange - (2702)'.
[Trace - 11:32:30 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:30 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:32:30 AM] Received response 'textDocument/completion - (2693)' in 2355ms.
[Trace - 11:32:30 AM] Received response 'textDocument/foldingRange - (2694)' in 2153ms.
[Trace - 11:32:30 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:30 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:32:30 AM] Sending request 'textDocument/signatureHelp - (2703)'.
[Trace - 11:32:31 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:31 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:32:31 AM] Sending request 'textDocument/signatureHelp - (2704)'.
[Trace - 11:32:31 AM] Sending request 'textDocument/foldingRange - (2705)'.
[Trace - 11:32:31 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:31 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:32:31 AM] Received response 'textDocument/completion - (2695)' in 2134ms.
[Trace - 11:32:31 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:31 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:32:31 AM] Sending request 'textDocument/signatureHelp - (2706)'.
[Trace - 11:32:31 AM] Received response 'textDocument/foldingRange - (2696)' in 2404ms.
[Trace - 11:32:31 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:32:31 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:31 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:32:31 AM] Sending request 'textDocument/signatureHelp - (2707)'.
[Trace - 11:32:31 AM] Sending request 'textDocument/foldingRange - (2708)'.
[Trace - 11:32:32 AM] Received response 'textDocument/foldingRange - (2697)' in 2548ms.
[Trace - 11:32:32 AM] Received response 'textDocument/semanticTokens/edits - (2698)' in 2330ms.
[Trace - 11:32:32 AM] Sending request 'textDocument/semanticTokens/edits - (2709)'.
[Trace - 11:32:32 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:32:32 AM] Received response 'textDocument/foldingRange - (2699)' in 2227ms.
[Trace - 11:32:32 AM] Sending request 'textDocument/documentSymbol - (2710)'.
[Trace - 11:32:32 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:32 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:32:32 AM] Received response 'textDocument/completion - (2700)' in 2466ms.
[Trace - 11:32:32 AM] Received response 'textDocument/signatureHelp - (2701)' in 2444ms.
[Trace - 11:32:32 AM] Received response 'textDocument/foldingRange - (2702)' in 2370ms.
[Trace - 11:32:33 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:33 AM] Sending request 'textDocument/signatureHelp - (2711)'.
[Trace - 11:32:33 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:33 AM] Sending request 'textDocument/signatureHelp - (2712)'.
[Trace - 11:32:33 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:32:33 AM] Received response 'textDocument/signatureHelp - (2703)' in 2588ms.
[Trace - 11:32:33 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:33 AM] Sending request 'textDocument/signatureHelp - (2713)'.
[Trace - 11:32:33 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:33 AM] Sending request 'textDocument/signatureHelp - (2714)'.
[Trace - 11:32:33 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:32:33 AM] Received response 'textDocument/signatureHelp - (2704)' in 2838ms.
[Trace - 11:32:33 AM] Received response 'textDocument/foldingRange - (2705)' in 2764ms.
[Trace - 11:32:33 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:33 AM] Sending request 'textDocument/signatureHelp - (2715)'.
[Trace - 11:32:34 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:34 AM] Sending request 'textDocument/signatureHelp - (2716)'.
[Trace - 11:32:34 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:34 AM] Sending request 'textDocument/signatureHelp - (2717)'.
[Trace - 11:32:34 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:32:34 AM] Received response 'textDocument/signatureHelp - (2706)' in 2723ms.
[Trace - 11:32:34 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:34 AM] Sending request 'textDocument/signatureHelp - (2718)'.
[Trace - 11:32:34 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:32:34 AM] Received response 'textDocument/signatureHelp - (2707)' in 2949ms.
[Trace - 11:32:34 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:34 AM] Sending request 'textDocument/signatureHelp - (2719)'.
[Trace - 11:32:35 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:35 AM] Sending request 'textDocument/signatureHelp - (2720)'.
[Trace - 11:32:35 AM] Sending notification '$/cancelRequest'.
[Trace - 11:32:35 AM] Sending request 'textDocument/signatureHelp - (2721)'.
[Trace - 11:32:35 AM] Received response 'textDocument/foldingRange - (2708)' in 3298ms.
[Trace - 11:32:35 AM] Received response 'textDocument/semanticTokens/edits - (2709)' in 2723ms.
[Trace - 11:32:35 AM] Received response 'textDocument/documentSymbol - (2710)' in 2495ms.
[Trace - 11:32:35 AM] Received response 'textDocument/signatureHelp - (2711)' in 2144ms.
[Trace - 11:32:35 AM] Received response 'textDocument/signatureHelp - (2712)' in 1913ms.
[Trace - 11:32:35 AM] Received response 'textDocument/signatureHelp - (2713)' in 1692ms.
[Trace - 11:32:35 AM] Received response 'textDocument/signatureHelp - (2714)' in 1490ms.
[Trace - 11:32:35 AM] Received response 'textDocument/signatureHelp - (2715)' in 1301ms.
[Trace - 11:32:35 AM] Received response 'textDocument/signatureHelp - (2716)' in 1114ms. Request failed: Request textDocument/signatureHelp failed with message: Cannot read property 'l' of undefined (-32603).
[Error - 11:32:35 AM] Request textDocument/signatureHelp failed.
  Message: Request textDocument/signatureHelp failed with message: Cannot read property 'l' of undefined
  Code: -32603 
[Trace - 11:32:35 AM] Received response 'textDocument/signatureHelp - (2717)' in 941ms.
[Trace - 11:32:35 AM] Received response 'textDocument/signatureHelp - (2718)' in 477ms. Request failed: Request textDocument/signatureHelp failed with message: Cannot read property 'l' of undefined (-32603).
[Error - 11:32:35 AM] Request textDocument/signatureHelp failed.
  Message: Request textDocument/signatureHelp failed with message: Cannot read property 'l' of undefined
  Code: -32603 
[Trace - 11:32:35 AM] Received response 'textDocument/signatureHelp - (2719)' in 300ms.
[Trace - 11:32:35 AM] Received response 'textDocument/signatureHelp - (2720)' in 160ms.
[Trace - 11:32:35 AM] Received response 'textDocument/signatureHelp - (2721)' in 12ms.
[Trace - 11:32:35 AM] Sending request 'textDocument/signatureHelp - (2722)'.
[Trace - 11:32:35 AM] Received response 'textDocument/signatureHelp - (2722)' in 0ms.

**Comment by isc-bsaviano** [comment] 2021-01-22 17:03
The "Request textDocument/signatureHelp failed." errors are being caused by textDocument/signatureHelp requests that have the isRetrigger property set to `true` and activeSignatureHelp set to `undefined`. The LS assumed this wasn't possible because it doesn't make much sense so the request would fail ungracefully instead of just returning `null`. I will fix this. Thanks to @mburstinisc for sending me his logs and beta testing.

**Closed** 2021-01-22 17:05 UTC
Labels: bug
