### ISSUE TITLE
Mixed colors

### ISSUE THREAD

**Issue by jtsalten** [intersystems/language-server#149] opened 2021-04-14 10:59 UTC
Issue Type: <b>Bug</b>

Editing code in a subroutine, all of a sudden, colors get mixed... even if ObjectScript code is perfectly right. In fact, closing and opening the file or VS code solves the issue...

Extension version: 1.1.4
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (2.29GB free)|
|Process Argv|--crash-reporter-id 358469c0-fdbf-4ba7-9019-19e4937e55fb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30283811
openwslfolder:30282073
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by jtsalten** [comment] 2021-04-14 11:01
It can be really worser... but in the image below you can see how it starts... see the mixed color in the comment in subroutine leer... and also how the quit commant is purple instead of white...

![image](https://user-images.githubusercontent.com/6997495/114700034-4f02d780-9d21-11eb-8a62-ca9c7412e3ec.png)

**Comment by isc-bsaviano** [comment] 2021-04-14 11:09
Duplicate of #29

@jtsalten Unfortunately, this is a bug in VSCode itself or the VSCode-languageclient module that our LS depends on.

**Closed** 2021-04-14 11:09 UTC
Labels: duplicate
