### ISSUE TITLE
Consider caching data to improve hover tip performance

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#110] opened 2020-12-16 18:24 UTC
In the following recording compare how long it takes for the %Persistent tip to appear compared to the %String one. The %Boolean one takes a bit longer than %String.

The class was opened from a remote server across the internet, using isfs.

![junk](https://user-images.githubusercontent.com/6726799/102389686-5d3b2400-3fcb-11eb-94e5-bc970e154c3d.gif)

Repeatedly hovering over %Persistent and then moving away always seems to take the same long time to yield the tip. Even if the slow response can't be improved the first time, can caching be used to make it faster next time?

Extension version: 1.0.6
VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (2.32GB free)|
|Process Argv|--enable-proposed-api intersystems-community.vscode-objectscript --crash-reporter-id a06af274-fb12-4e73-ba12-3b17f2a1510f|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isc-bsaviano** [comment] 2020-12-16 18:39
@gjsjohnmurray Have you experienced this behavior with previous versions using the same IRIS instance? The only change that affects hover info for class names is the addition of turndown, which converts HTML to Markdown. Using 1.0.6 on my Mac connected to a local IRIS, class name hovers return in 10-15ms. If you try with a local instance, do you still see a performance hit?

**Comment by gjsjohnmurray** [comment] 2020-12-16 19:30
I hadn't noticed it before, but I hadn't been testing hovers.

Connecting to a local instance I don't see any delay.

It takes about as long to get the hover result as it takes to see a new tab open if I use "Go to Definition" from the context menu. I'm guessing you retrieve the entire class definition each time I hover, right?

**Comment by isc-bsaviano** [comment] 2020-12-16 19:37
@gjsjohnmurray I don't cache any results from hovering/go to definition. For hovering over a class name, I make a POST /action/index request for that class to get the description. It sounds like the issue is that your network is slow if both hovering and go to definition are affected.

**Comment by gjsjohnmurray** [comment] 2020-12-16 19:47
Yes, I accept that the path to my server is a slow one.

Puzzling that the hover over %String is faster than the hover over %Boolean, even though %Library.String.cls has 169 lines and %Library.Boolean.cls has only 62. Certainly %Library.Persistent is a lot bigger (1854 lines).

Maybe a future enhancement could do more caching?

**Comment by isc-bsaviano** [comment] 2020-12-16 19:48
For the specific case of hovering over a class name, I could replace the POST /action/index call with a POST /action/query call that only returns the exact info that I need (just the description). Testing on a local IRIS using Postman, here's what the benefit looks like for %Persistent:

POST /action/index (current behavior)
```json
["%Library.Persistent.cls"]
```
Returns 76.25KB of data in ~14ms

POST /action/query (proposed behavior)
```json
{
    "query": "SELECT Description FROM %Dictionary.CompiledClass WHERE Name = ?",
    "parameters": ["%Library.Persistent"]
}
```
Returns 684B of data in ~8ms

While this isn't a meaningful change when you're connected to a local IRIS or one on a fast network, transferring ~75KB fewer would likely be noticeable on a slower network like yours.

**Comment by gjsjohnmurray** [comment] 2020-12-16 19:49
Yes please!

**Comment by isc-bsaviano** [comment] 2020-12-16 19:51
@gjsjohnmurray I will open a separate enhancement request for the POST /action/index -> POST /action/query replacement so this issue can be for caching specifically. Can you edit the title/description to clarify that this is a request for caching?

**Comment by isc-jamien** [comment] 2020-12-17 15:59
Addressing the issue of Caching. There is already a facility for pre-populating an index. These are delivered in /dev/atelier/{database}/METADATA.zip file and can be retrieved via a call to the Atelier APIs. Atelier does this to cache the static metadata for particular instances. I think a separate extension that can retrieve these files, and store them locally in a version specific location and intercept the metadata calls would be a future possibility but for now that is not a priority.

**Closed** 2020-12-17 16:07 UTC
Labels: enhancement, won't do
