### ISSUE TITLE
Spurious "Class does not exist" after `zNSpace` or `Set $NAMESPACE`

### ISSUE THREAD

**Issue by isc-aray** [intersystems/language-server#177] opened 2021-07-22 13:29 UTC
When a method or classmethod switches to another namespace using the `zNSpace` command or by `Set`ting `$NAMESPACE`, Language Server continues to look for referenced classes in the original namespace. For example, this class will show an error if opened in the `USER` namespace:

```objectscript
Class Demo.Reproduce
{

Method Demo()
{
    New $NAMESPACE zNSpace "%SYS"
    Set query=##CLASS(Security.Roles).ListAllFunc()
}

}
```

Language server will report "Class 'Security.Roles' does not exist." However, this error is spurious, because while the class does not exist in the `USER` namespace, it does exist in the `%SYS` namespace. This class will compile and the method can be run without issue.

Following a `zNSpace` command or `Set $NAMESPACE` statement, Language Server should look for classes in the new namespace, or if that is not possible, should not attempt to check for classes at all.

**Comment by jaynewt1959** [comment] 2021-07-22 13:36
It's not reasonable (nor desirable) to have the parser attempt to evaluate object script code to discover contextual. That behavior is limited to runtime, not compile time. We will not be changing this behavior.

**Comment by isc-bsaviano** [comment] 2021-07-22 13:37
Closing as duplicate of #77

**Closed by isc-bsaviano** 2021-07-22 13:37 UTC
Labels: duplicate

**Comment by bourette** [comment] 2021-07-22 13:47
> It's not reasonable (nor desirable) to have the parser attempt to evaluate object script code to discover contextual. That behavior is limited to runtime, not compile time. We will not be changing this behavior.

Although it's not desirable to have the parser attempt to evaluate this it would be nice if there was a directive to help the parser resolve this.  It's annoying to have code tell you there is a problem when there isn't.

**Comment by jaynewt1959** [comment] 2021-07-22 13:57
Apart from littering your source code with directives that only affect a particular IDE implementation doesn't seem like a reasonable thing either. It would take a tremendous amount of work to implement that (updates to the parsers, macro preprocessor, compiler etc etc). This is a definite won't do

**Comment by isc-aray** [comment] 2021-07-22 14:00
It's fully unreasonable to have the IDE tell me that good code is bad code. If there is a workaround, I'd love to know what it is, but otherwise, this makes language-server completely useless to me. If I have to hunt through a pile of spurious issues to find real ones, I'd rather just disable error checking altogether.

**Comment by bourette** [comment] 2021-07-22 14:03
Use $classmethod instead.

**Comment by isc-bsaviano** [comment] 2021-07-22 14:03
@isc-aray You can turn "class does not exist" errors off. The setting is `intersystems.language-server.diagnostics.classes`.

**Comment by bourette** [comment] 2021-07-22 14:04
I think turning it off completely is a mistake.

**Comment by isc-bsaviano** [comment] 2021-07-22 14:06
@bourette The diagnostics will remain on by default, I was just showing Andrew how to turn them off if he wants to.
