### ISSUE TITLE
Syntax error on columns started with _

### ISSUE THREAD

**Issue by daimor** [intersystems/language-server#279] opened 2023-05-15 14:38 UTC
This is generated class HSFHIR.X0001.S.Observation

<img width="590" alt="image" src="https://github.com/intersystems/language-server/assets/1212251/6a923285-d146-4152-83bc-0b78e8391090">

**Comment by isc-bsaviano** [comment] 2023-05-15 14:52
Can you tell me more about what class(es) generate this one? I think this syntax is incorrect. The property name should be quoted and it is colored correctly if so.

**Comment by daimor** [comment] 2023-05-15 14:58
`GeneratedBy = HS.FHIRServer.Storage.SearchTableBuilder.CLS`
Actually, all classes generated for FHIR in package `HSFHIR.X0001.S` gets these indexes
You would need to install FHIR server in IRIS to see them, for instance with `zpm "install fhir-server"`

**Comment by isc-bsaviano** [comment] 2023-05-15 15:44
Closing because this is not a bug in this extension, but I will investigate further

**Closed by isc-bsaviano** 2023-05-15 15:44 UTC
