### ISSUE TITLE
Cube Definition syntax highlight bug

### ISSUE THREAD

**Issue by v23ent** [intersystems/language-server#49] opened 2020-10-28 08:08 UTC
You can see it on a screenshot.
Not sure if it's somehow influenced by Cyrillic chars...

<img width="1154" alt="Снимок экрана 2020-10-28 в 11 02 05" src="https://user-images.githubusercontent.com/12609489/97408615-63871b00-190d-11eb-8267-49ead6f31397.png">

```
/// 
Class isc.ecom.bi.OrderItemsCube Extends %DeepSee.CubeDefinition [ DependsOn = isc.ecom.model.OrderItem, ProcedureBlock ]
{

/// Cube definition from Architect.
XData Cube [ XMLNamespace = "http://www.intersystems.com/deepsee" ]
{
<cube xmlns="http://www.intersystems.com/deepsee" name="OrderItemsCube" displayName="Заказы (строки)" disabled="false" abstract="false" sourceClass="isc.ecom.model.OrderItem" namedFactNums="true" countMeasureName="%COUNT" countMeasureCaption="Продажи (записей)" bucketSize="8" bitmapChunkInMemory="false" precompute="0" disableListingGroups="false" enableSqlRestrict="false">
  <dimension name="CreateDateTime" displayName="Дата заказа" disabled="false" hasAll="true" allCaption="AllDates" allDisplayName="Все даты" sourceProperty="order.orderedAt" type="time" calendar="gregorian" iKnowType="entity" hidden="false" showHierarchies="default">
    <hierarchy name="H1" disabled="false" hidden="false">
      <level name="Year" displayName="Год" disabled="false" timeFunction="Year" list="false" useDisplayValue="true" sort="desc" useAsFilter="true" hidden="false" factNumber="2">
      </level>
      <level name="Month" displayName="Месяц" disabled="false" timeFunction="MonthYear" list="false" useDisplayValue="true" sort="desc" useAsFilter="true" hidden="false" factNumber="3">
      </level>
      <level name="Week" displayName="Неделя" disabled="false" timeFunction="WeekYear" list="false" useDisplayValue="true" sort="desc" useAsFilter="true" hidden="false" factNumber="12">
      </level>
      <level name="Date" displayName="Дата" disabled="false" timeFunction="DayMonthYear" timeFormat="dd.mm.y" list="false" useDisplayValue="true" sort="desc" useAsFilter="true" hidden="false" factNumber="4">
      </level>
    </hierarchy>
  </dimension>
</cube>
}

/// Gets product category name
ClassMethod getProductCategory(pProductId As %String, pName As %String = "") As %String
{
  set product = ##class(isc.ecom.model.Product).%OpenId(pProductId)
  return:'$isobject(product) ""

  set category = product.getCategory(pName)
  return $get(category, "")
}

Parameter DOMAIN;

}
```

**Comment by gjsjohnmurray** [comment] 2020-10-28 08:29
Probably a duplicate of #31

**Comment by isc-bsaviano** [comment] 2020-10-28 12:53
@v23ent Closing this since it's a duplicate.

**Closed by isc-bsaviano** 2020-10-28 12:53 UTC

**Comment by gjsjohnmurray** [comment] 2020-10-28 17:32
@v23ent please update Language Server to 1.0.4 and verify this is fixed.
