### ISSUE TITLE
Crashes on editing some classes

### ISSUE THREAD

**Issue by CoffeeMonster42** [intersystems/language-server#306] opened 2024-02-21 07:52 UTC
On editing some classes the language server is crashing with this output

[Error - 9:49:21 AM] Server process exited with code 3221225477.
[Info  - 9:49:21 AM] Connection to server got closed. Server will restart.
true

**Comment by gjsjohnmurray** [comment] 2024-02-21 09:04
I suggest you alter the `intersystems.language-server.trace.server` to get extra information in the InterSystems Language Server channel of the Output view (normally in the Panel). Take care not to post sensitive information here. If it isn't easy to mask before posting please create a WRC ticket and attach the output there, then quote the ticket number here.

**Comment by CoffeeMonster42** [comment] 2024-02-21 10:05
I will try WRC then.

**Comment by CoffeeMonster42** [comment] 2024-02-21 12:07
Version is 2.4.3
I've attached the .cls file
[SalesOrder.zip](https://github.com/intersystems/language-server/files/14359194/SalesOrder.zip)

**Comment by CoffeeMonster42** [comment] 2024-02-21 13:20
$zv is 
IRIS for Windows (x86-64) 2022.1 (Build 209U) Tue May 31 2022 12:16:40 EDT

**Comment by isc-bsaviano** [comment] 2024-02-21 13:21
Thanks. Let me see what information I can gather.

**Comment by isc-bsaviano** [comment] 2024-02-21 15:13
After speaking to the SQL team, this appears to be caused by a bug that was fixed in IRIS 2022.1.3 (YCL157). I recommend upgrading to a version with the fix and tuning your tables again. The WRC can help with that.

**Comment by isc-bsaviano** [comment] 2024-02-22 17:59
@CoffeeMonster42 Even though I was able to reproduce the crash I'm going to close this because the code that caused the crash was buggy. An immediate workaround is to re-tune your table or remove the tune table statistics from the class. I recommend that you upgrade to a version with the fix that I mentioned.

**Closed by isc-bsaviano** 2024-02-22 17:59 UTC

**Comment by CoffeeMonster42** [comment] 2024-02-22 19:31
Thanks.

Do you know how I can remove the stats from the class?
