### ISSUE TITLE
zwrite supports any expression not only variables

### ISSUE THREAD

**Issue by daimor** [intersystems/language-server#94] opened 2020-11-18 14:59 UTC
https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=RCOS_czwrite

![image](https://user-images.githubusercontent.com/1212251/99546310-5b2f7680-29c7-11eb-92ee-db620cff5555.png)

![image](https://user-images.githubusercontent.com/1212251/99546419-70a4a080-29c7-11eb-9a0d-9cb64774ffeb.png)

```
  ZWrite var,1*2,var2
  ZWrite 1+1
  ZWrite $zv,var
  ZWrite $this
```

**Comment by isc-bsaviano** [comment] 2020-11-18 15:07
@daimor I'll pass this along to Andy

**Comment by isc-bsaviano** [comment] 2020-11-18 15:13
May be a duplicate of #56

**Comment by daimor** [comment] 2020-11-18 15:15
Yeah, it's actually the same, but I have an addition, that it should support any expression, not syntax provided there.

**Comment by isc-bsaviano** [comment] 2020-11-18 15:17
Yes, it looks like #56 is a subset of this issue. I'll leave both open so I know to test all cases when Andy makes the change.

**Closed** 2020-12-03 15:56 UTC
Labels: parser
