### ISSUE TITLE
Parameter value and type do not match

### ISSUE THREAD

**Issue by bourette** [intersystems/language-server#57] opened 2020-11-02 15:05 UTC
Issue Type: <b>Bug</b>

Language server reports Parameter value and type do not match for macro, ie
Parameter RESOURCE As STRING = {$$$HSHubManagement};

Extension version: 1.0.4
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

**Comment by isc-bsaviano** [comment] 2020-11-02 15:36
@bourette The LS checks if the token immediately following the "=" is a string literal if the declared type is STRING. There's no way for it to know that a macro will resolve to a string. I will discuss with the Jamie about the best way to handle gaps like this in the parameter checking. While we figure this out you can turn parameter diagnostics off in the extension settings.

**Comment by isc-bsaviano** [comment] 2020-11-02 15:47
@bourette Jamie and I decided that if you declare a parameter type as STRING and the right hand side is a COS expression, we're going to assume that the user knows what they're doing and not report the warning.

**Comment by isc-bsaviano** [comment] 2020-11-02 15:56
@bourette According to our docs, your syntax is wrong. You're not supposed to type a parameter when using curly braces: https://docs.intersystems.com/irislatest/csp/docbook/Doc.View.cls?KEY=GOBJ_parameters#GOBJ_parameters_curly

I'm closing this issue because it's not a bug with the LS

**Closed by isc-bsaviano** 2020-11-02 15:56 UTC
Labels: bug
