### ISSUE TITLE
Parsing Error: Language server does not detect namespace switch in code

### ISSUE THREAD

**Issue by mfortuna-isc** [intersystems/language-server#206] opened 2021-12-09 15:14 UTC
# Summary 
![image](https://user-images.githubusercontent.com/95868869/145421072-c4e5d4de-4469-43cf-b3da-1720c5d6e7bf.png)
 In my small method, I switch to the %SYS namespace which maps to the database containing class `Config.Namespaces`. On return, the namespace switches back to the namespace of the calling method. This is a common pattern described here:  [docs](https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=RCOS_VNAMESPACE).
However, the language server says that `Config.Namespaces` DNE, even though it does in the `%SYS` namespace, and I have properly switched to that namespace in my code. (Yes my code runs properly).
# Problem
The language server is flagging `##class(Config.Namespaces)` as DNE, even though my method has switched to the proper namespace containing that class.`Config.Namespace` ( ie. `%SYS`)
# What I expect
I expect the language server to flag no error because it would detect that my method has switched to the `%SYS` namespace, which contains `Config.Namespace.cls` ,

**Comment by isc-bsaviano** [comment] 2021-12-09 15:16
Duplicate of #77 & #177

**Closed by isc-bsaviano** 2021-12-09 15:16 UTC

**Comment by mfortuna-isc** [comment] 2021-12-09 16:16
Ah. I'll search through closed issues next time. (Forgot about the default is open filter). Thanks
